[2023-11-23T04:49:45.655+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:49:42.186135+00:00 [queued]>
[2023-11-23T04:49:45.671+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:49:42.186135+00:00 [queued]>
[2023-11-23T04:49:45.672+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:49:45.672+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-23T04:49:45.672+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:49:45.693+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-11-23 04:49:42.186135+00:00
[2023-11-23T04:49:45.699+0000] {standard_task_runner.py:55} INFO - Started process 1803 to run task
[2023-11-23T04:49:45.703+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'is_api_available', 'manual__2023-11-23T04:49:42.186135+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpisv89obx']
[2023-11-23T04:49:45.706+0000] {standard_task_runner.py:83} INFO - Job 303: Subtask is_api_available
[2023-11-23T04:49:45.790+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:49:42.186135+00:00 [running]> on host f71f95879a41
[2023-11-23T04:49:45.877+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T04:49:42.186135+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-23T04:49:42.186135+00:00
[2023-11-23T04:49:45.879+0000] {http.py:120} INFO - Poking: api/
[2023-11-23T04:49:45.892+0000] {base.py:71} INFO - Using connection ID 'rand_user_api' for task execution.
[2023-11-23T04:49:45.894+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-11-23T04:49:47.061+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-11-23T04:49:47.099+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=rand_user, task_id=is_api_available, execution_date=20231123T044942, start_date=20231123T044945, end_date=20231123T044947
[2023-11-23T04:49:47.161+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-23T04:49:47.205+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
