[2023-11-08T06:36:32.961+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: US_population.Create_table scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T06:36:32.981+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: US_population.Create_table scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T06:36:32.981+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T06:36:32.982+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-08T06:36:32.983+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T06:36:33.012+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): Create_table> on 2023-11-07 00:00:00+00:00
[2023-11-08T06:36:33.021+0000] {standard_task_runner.py:55} INFO - Started process 3357 to run task
[2023-11-08T06:36:33.027+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'US_population', 'Create_table', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpuzcjpxl_']
[2023-11-08T06:36:33.030+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask Create_table
[2023-11-08T06:36:33.120+0000] {task_command.py:376} INFO - Running <TaskInstance: US_population.Create_table scheduled__2023-11-07T00:00:00+00:00 [running]> on host 91f7624ceef9
[2023-11-08T06:36:33.261+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=US_population
AIRFLOW_CTX_TASK_ID=Create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-07T00:00:00+00:00
[2023-11-08T06:36:33.283+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-08T06:36:33.291+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS US_users (
        ID_Nation TEXT NOT NULL,
        Nation TEXT NOT NULL,
        ID_Year int NOT NULL,
        year TEXT NOT NULL,
        Population BIGINT NOT NULL,
        Slug_Nation TEXT NOT NULL
        )
        , parameters: None
[2023-11-08T06:36:33.293+0000] {postgres.py:96} INFO - NOTICE:  relation "us_users" already exists, skipping

[2023-11-08T06:36:33.313+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=US_population, task_id=Create_table, execution_date=20231107T000000, start_date=20231108T063632, end_date=20231108T063633
[2023-11-08T06:36:33.364+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-08T06:36:33.398+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
