[2023-11-22T06:35:41.399+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.destinatin_table manual__2023-11-22T06:35:27.687831+00:00 [queued]>
[2023-11-22T06:35:41.420+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.destinatin_table manual__2023-11-22T06:35:27.687831+00:00 [queued]>
[2023-11-22T06:35:41.421+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T06:35:41.421+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-22T06:35:41.422+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T06:35:41.449+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): destinatin_table> on 2023-11-22 06:35:27.687831+00:00
[2023-11-22T06:35:41.458+0000] {standard_task_runner.py:55} INFO - Started process 1134 to run task
[2023-11-22T06:35:41.465+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'destinatin_table', 'manual__2023-11-22T06:35:27.687831+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpy45tahcb']
[2023-11-22T06:35:41.468+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask destinatin_table
[2023-11-22T06:35:41.570+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.destinatin_table manual__2023-11-22T06:35:27.687831+00:00 [running]> on host e4a6f7cdd654
[2023-11-22T06:35:41.702+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=destinatin_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T06:35:27.687831+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-22T06:35:27.687831+00:00
[2023-11-22T06:35:41.721+0000] {base.py:71} INFO - Using connection ID 'pgadmin_dest_connection' for task execution.
[2023-11-22T06:35:41.730+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS rand_dest_users (
        gender TEXT NOT NULL,
        title TEXT NOT NULL,
        firstname TEXT NOT NULL,
        lastname TEXT NOT NULL,
        country TEXT NOT NULL,
        username TEXT NOT NULL,
        password TEXT NOT NULL,
        email TEXT NOT NULL,
        age INT NOT NULL
        )
        , parameters: None
[2023-11-22T06:35:41.734+0000] {postgres.py:96} INFO - NOTICE:  relation "rand_dest_users" already exists, skipping

[2023-11-22T06:35:41.750+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=rand_user, task_id=destinatin_table, execution_date=20231122T063527, start_date=20231122T063541, end_date=20231122T063541
[2023-11-22T06:35:41.796+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-22T06:35:41.845+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
