[2023-11-23T04:27:43.685+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:27:41.562486+00:00 [queued]>
[2023-11-23T04:27:43.697+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:27:41.562486+00:00 [queued]>
[2023-11-23T04:27:43.697+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:27:43.698+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-23T04:27:43.698+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:27:43.713+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-11-23 04:27:41.562486+00:00
[2023-11-23T04:27:43.720+0000] {standard_task_runner.py:55} INFO - Started process 681 to run task
[2023-11-23T04:27:43.724+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'is_api_available', 'manual__2023-11-23T04:27:41.562486+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpz5l3kvl6']
[2023-11-23T04:27:43.726+0000] {standard_task_runner.py:83} INFO - Job 274: Subtask is_api_available
[2023-11-23T04:27:43.791+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.is_api_available manual__2023-11-23T04:27:41.562486+00:00 [running]> on host f71f95879a41
[2023-11-23T04:27:43.886+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T04:27:41.562486+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-23T04:27:41.562486+00:00
[2023-11-23T04:27:43.887+0000] {http.py:120} INFO - Poking: api/
[2023-11-23T04:27:43.896+0000] {base.py:71} INFO - Using connection ID 'rand_user_api' for task execution.
[2023-11-23T04:27:43.898+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-11-23T04:27:44.309+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-11-23T04:27:44.324+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=rand_user, task_id=is_api_available, execution_date=20231123T042741, start_date=20231123T042743, end_date=20231123T042744
[2023-11-23T04:27:44.377+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-23T04:27:44.417+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
