[2023-11-23T04:48:14.002+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Data_transfer.Create_source_table scheduled__2023-11-23T04:18:04.853042+00:00 [queued]>
[2023-11-23T04:48:14.012+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Data_transfer.Create_source_table scheduled__2023-11-23T04:18:04.853042+00:00 [queued]>
[2023-11-23T04:48:14.013+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:48:14.013+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-23T04:48:14.013+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T04:48:14.027+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): Create_source_table> on 2023-11-23 04:18:04.853042+00:00
[2023-11-23T04:48:14.034+0000] {standard_task_runner.py:55} INFO - Started process 1716 to run task
[2023-11-23T04:48:14.039+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_transfer', 'Create_source_table', 'scheduled__2023-11-23T04:18:04.853042+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/data_transfer.py', '--cfg-path', '/tmp/tmpd8kn4u6e']
[2023-11-23T04:48:14.040+0000] {standard_task_runner.py:83} INFO - Job 298: Subtask Create_source_table
[2023-11-23T04:48:14.106+0000] {task_command.py:376} INFO - Running <TaskInstance: Data_transfer.Create_source_table scheduled__2023-11-23T04:18:04.853042+00:00 [running]> on host f71f95879a41
[2023-11-23T04:48:14.176+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=Data_transfer
AIRFLOW_CTX_TASK_ID=Create_source_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T04:18:04.853042+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T04:18:04.853042+00:00
[2023-11-23T04:48:14.186+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-23T04:48:14.195+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS source_table (
        uuid TEXT NOT NULL,
        title TEXT NOT NULL,
        firstname TEXT NOT NULL,
        lastname TEXT NOT NULL,
        gender TEXT NOT NULL,
        country TEXT NOT NULL,
        username TEXT NOT NULL,
        password TEXT NOT NULL,
        email TEXT NOT NULL,
        age INT NOT NULL
        )
        , parameters: None
[2023-11-23T04:48:14.201+0000] {postgres.py:96} INFO - NOTICE:  relation "source_table" already exists, skipping

[2023-11-23T04:48:14.231+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Data_transfer, task_id=Create_source_table, execution_date=20231123T041804, start_date=20231123T044814, end_date=20231123T044814
[2023-11-23T04:48:14.290+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-23T04:48:14.326+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
