[2023-11-23T05:20:35.818+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.create_destinatin_table manual__2023-11-23T05:20:27.492967+00:00 [queued]>
[2023-11-23T05:20:35.830+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.create_destinatin_table manual__2023-11-23T05:20:27.492967+00:00 [queued]>
[2023-11-23T05:20:35.830+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T05:20:35.831+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-23T05:20:35.831+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T05:20:35.846+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_destinatin_table> on 2023-11-23 05:20:27.492967+00:00
[2023-11-23T05:20:35.852+0000] {standard_task_runner.py:55} INFO - Started process 3398 to run task
[2023-11-23T05:20:35.856+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'create_destinatin_table', 'manual__2023-11-23T05:20:27.492967+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpqvs085ax']
[2023-11-23T05:20:35.858+0000] {standard_task_runner.py:83} INFO - Job 352: Subtask create_destinatin_table
[2023-11-23T05:20:35.924+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.create_destinatin_table manual__2023-11-23T05:20:27.492967+00:00 [running]> on host f71f95879a41
[2023-11-23T05:20:35.999+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=create_destinatin_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T05:20:27.492967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-23T05:20:27.492967+00:00
[2023-11-23T05:20:36.009+0000] {base.py:71} INFO - Using connection ID 'dest_conn_id' for task execution.
[2023-11-23T05:20:36.017+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS rand_dest_users (
        gender TEXT NOT NULL,
        title TEXT NOT NULL,
        firstname TEXT NOT NULL,
        lastname TEXT NOT NULL,
        country TEXT NOT NULL,
        username TEXT NOT NULL,
        password TEXT NOT NULL,
        email TEXT NOT NULL,
        age INT NOT NULL
        )
        , parameters: None
[2023-11-23T05:20:36.020+0000] {postgres.py:96} INFO - NOTICE:  relation "rand_dest_users" already exists, skipping

[2023-11-23T05:20:36.030+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=rand_user, task_id=create_destinatin_table, execution_date=20231123T052027, start_date=20231123T052035, end_date=20231123T052036
[2023-11-23T05:20:36.067+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-23T05:20:36.117+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
